### ISSUE TITLE
Tests for flask API’s

### ISSUE THREAD

**Issue by Tushar19varshney** [scorelab/fact-Bounty#104]
Hi @ivantha!
We should add some tests for flask API’s . It would help us in **continuous integration** and for easy testing of our API’s .I am working on tests for the last couple of days and will make a PR soon.

**Thanks**

**Comment by Tushar19varshney** [comment]
![screenshot from 2019-03-06 00-42-07](https://user-images.githubusercontent.com/34132255/53830622-e9bc5400-3fa8-11e9-9141-0bee301ed1f3.png)

@ivantha 
I am facing a problem regarding importing module and this is my projects structure
![screenshot from 2019-03-06 00-51-54](https://user-images.githubusercontent.com/34132255/53831162-276dac80-3faa-11e9-94e6-3a0e56a121da.png)

**Comment by Tushar19varshney** [comment]
Should i change the directory name from `fact-bounty-flask` to `fact_bounty_flask` as invalid syntax error comes when we try to import dashed file name in python?

**Comment by ivantha** [comment]
> Should i change the directory name from `fact-bounty-flask` to `fact_bounty_flask` as invalid syntax error comes when we try to import dashed file name in python?

Is there any other way to achieve this without renaming the directory?

**Comment by Anmolbansal1** [comment]
It's done in https://github.com/scorelab/fact-Bounty/pull/135

**Comment by Tushar19varshney** [comment]
@ivantha 
The error was solved without changing the name and I had created a PR with the tests!
**Thanks**
