### ISSUE TITLE
Register option in NavBar menu

### ISSUE THREAD

**Issue by sweezy793** [scorelab/fact-Bounty#105]
# Expected Behavior

There should be a register option under login in navbar menu

# Current Behavior

Right now register can only be accessed by manually going to the route
![screenshot_20190304_144346](https://user-images.githubusercontent.com/23583306/53722630-0151ea80-3e8c-11e9-9055-fd968e6439a3.png)

## Steps to Reproduce

A similar menu item such as login which point to /register needs to be added

**Comment by Anmolbansal1** [comment]
Duplicate of #67

**Comment by sweezy793** [comment]
#67 said it there is no register option from login page. This is about no register option in navbar

**Comment by sweezy793** [comment]
> Duplicate of #67

#67 said it there is no register option from login page. This is about no register option in navbar

**Comment by Anmolbansal1** [comment]
Ohk, sorry about that
