### ISSUE TITLE
Live reload flask app

### ISSUE THREAD

**Issue by Anmolbansal1** [scorelab/fact-Bounty#116]
# Prerequisites

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
There should be live reload feature

# Current Behavior
Currently we need to reload flask app each time to see changes  

We can use livereload package

**Comment by Anmolbansal1** [comment]
I am working on this issue

**Comment by root5533** [comment]
What is the status of the fix @Anmolbansal1 ?
