### ISSUE TITLE
Logout button in navbar when logged in

### ISSUE THREAD

**Issue by sweezy793** [scorelab/fact-Bounty#128]
# Expected Behavior

Logout should be displayed in navbar when user is logged in.

# Current Behavior

Currently when user is logged in, navbar stays static and shows login and sign up

**Comment by RMCoder198** [comment]
@sweezy793 
 Are you working on it?

**Comment by sweezy793** [comment]
> @sweezy793
> Are you working on it?

Yes, I will be working on this

**Comment by root5533** [comment]
#169 fixes this issue
