### ISSUE TITLE
Show username in navbar after login

### ISSUE THREAD

**Issue by Kanishka5** [scorelab/fact-Bounty#134]
After login username will be visible beside logout button

**Comment by sweezy793** [comment]
Right now username doesn't exist, also using the full name or email id won't be appropriate.

**Comment by Kanishka5** [comment]
> Right now username doesn't exist, also using the full name or email id won't be appropria

> Right now username doesn't exist, also using the full name or email id won't be appropriate.

I was thinking of using first name
but i guess this change can wait till a username field is added in registration form
