### ISSUE TITLE
Use environment variables for MONGO_URI and secretKey in keys.js

### ISSUE THREAD

**Issue by georgeben** [scorelab/fact-Bounty#137]
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
The MONGO_URI and secretKey are sometimes sensitive information and they should be stored as environment variables.

# Current Behavior
The MONGO_URI and secretKey is hardcoded into the keys.js file

**Comment by Tushar19varshney** [comment]
@georgeben
We are not pushing any sensitive information on Github, that's why `keys.example.js` file is there.
Although all the API's had been shifted to `Flask` and `NodesJs` API's will shortly removed.

**Comment by georgeben** [comment]
Oh, never knew that. Thank you.
