### ISSUE TITLE
Use async await instead of callbacks

### ISSUE THREAD

**Issue by georgeben** [scorelab/fact-Bounty#138]
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
Use a clear readable syntax for handling asynchronous operations

# Current Behavior
Code uses callbacks for handling asynchronous operations. Callbacks make code a bit more difficult to maintain and scale.

**Comment by DeViL3998** [comment]
I am well versed in async await functions. I want to do this.

**Comment by Anmolbansal1** [comment]
Since api has been shifted to flask, this issue is now deprecated
