### ISSUE TITLE
Assert checks in unittest of Flask API's

### ISSUE THREAD

**Issue by Tushar19varshney** [scorelab/fact-Bounty#150]
`assert` checks in Flask API's needs to be updated as mentioned in the [unittest docs](https://docs.python.org/2/library/unittest.html).
Codacy was also showing error.

I am working on this!
**Thanks** :slightly_smiling_face:

**Comment by ivantha** [comment]
@Tushar19varshney When you mention issues in PRs, use "Closes #id" so that they get closed automatically.
