### ISSUE TITLE
Voting apis are not working in Flask server

### ISSUE THREAD

**Issue by root5533** [scorelab/fact-Bounty#156]
# Expected Behavior

When voting for posts, the server should return updated post response

# Current Behavior

A KeyError occurs when retrieving data from POST request at flask server. Response code is 400.

**Comment by Tushar19varshney** [comment]
Hi @root5533 
I have checked all API's of updating votes and they are working fine
Can you specify which API has given this error?
**Thanks**

**Comment by root5533** [comment]
The upvote downvote APIs do not work. How did you test them?

**Comment by Tushar19varshney** [comment]
By Postman, this is the form data I have been submitting:

**/api/stories/change-upvote-count**
```json
{
"story_id": "1",
"change_val":"12"
}
```
![Screenshot from 2019-03-10 15-33-11](https://user-images.githubusercontent.com/34132255/54083475-e67aec80-4349-11e9-8440-d2a2faa1bf59.png)

**Comment by root5533** [comment]
Here is the screenshot of the error when sending the request from react using axios.

![image](https://user-images.githubusercontent.com/19800005/54085143-690ea680-4360-11e9-915a-ef2b2eb17f44.png)

Also yes it seems to work when submitting as form-data in postman. But not from front-end
