### ISSUE TITLE
Post Login redirect

### ISSUE THREAD

**Issue by Kanishka5** [scorelab/fact-Bounty#185]
# Expected Behavior

Once the user successfully login they should be redirected to the homepage.

# Current Behavior

After a successful login dashboard is displayed, staying in the same page.

# Failure Information (for bugs)

Once the user login they should be redirected to a page that provides the main contents of the website, in our case the homepage which will show all the news items.

## Steps to Reproduce
1. Login using correct credentials.

**Comment by ayush221b** [comment]
I don't think that's the idea. @ivantha Could you please clarify?
