### ISSUE TITLE
Standard Project Proposal template for GSOC

### ISSUE THREAD

**Issue by Tushar19varshney** [scorelab/fact-Bounty#192]
As the deadline for submitting the project proposal is getting nearer, by adding a standard template would help us in making proposals.
@ivantha @root5533 @SamTube405

**Comment by Tushar19varshney** [comment]
Should I add the google guidelines as mentioned in [Google Summer of Code Guidelines](https://google.github.io/gsocguides/student/writing-a-proposal) as PROPOSAL.md file

**Comment by Kanishka5** [comment]
SCoRe Lab has a proposal template in the GSoC 2019 section http://www.scorelab.org/gsoc-2019/,
https://docs.google.com/document/d/1be2y09Z51yB9X69A04O1rsD9XQXTVLJtu9mvxZdbNpM/edit 
maybe it can be added as proposal.md

**Comment by Tushar19varshney** [comment]
@Kanishka5 Thanks for sharing :slightly_smiling_face:

**Comment by Tushar19varshney** [comment]
> Should I add the google guidelines as mentioned in [Google Summer of Code Guidelines](https://google.github.io/gsocguides/student/writing-a-proposal) as PROPOSAL.md file ?

@ivantha?

**Comment by Tushar19varshney** [comment]
@ivantha
Should the Proposal.md file added to the project ?

**Comment by ivantha** [comment]
GSoC project guidelines are not needed to be included in the repository.

**Comment by Tushar19varshney** [comment]
> GSoC project guidelines are not needed to be included in the repository.

:+1: **Thanks**
