### ISSUE TITLE
Cannot find module './config/keys'

### ISSUE THREAD

**Issue by Pradip-001** [scorelab/fact-Bounty#20]
There is no module named keys in config folder.

**Comment by Tushar19varshney** [comment]
There is a file `keys.example.js` in the config folder, you have to change that file to `keys.js` and fill your secret or private key in the json object.

**Comment by Pradip-001** [comment]
Thanks @Tushar19varshney , i will create keys.js file and replace "MONGO_URL" with "mongodb://localhost:27017/<db-name>"
