### ISSUE TITLE
error handling of Login and Register form , proxy port should changed to default flask port

### ISSUE THREAD

**Issue by Tushar19varshney** [scorelab/fact-Bounty#203]
The proxy port should be changed to 5000 same as Flask server default port 
I have also found that some error handling is missing from login and register forms like:
In Register form:
![ezgif com-optimize](https://user-images.githubusercontent.com/34132255/54626602-7ed64700-4a97-11e9-8b14-001c8f0cacc1.gif)

In the above video, the user is redirected to login without informed that he/she has already been registered!

In Login form:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34132255/54627169-e0e37c00-4a98-11e9-840e-995d77bb1138.gif)

In the above video, the user entered the wrong credentials but not getting the error!

I am working on this issue :slightly_smiling_face: 
**Thanks**

**Comment by ivantha** [comment]
Please use proper title next time.
