### ISSUE TITLE
Style improvement in Login and Register page

### ISSUE THREAD

**Issue by kartikpandey2** [scorelab/fact-Bounty#207]
# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior
Text inside input fields are cut from the bottom
![Screenshot (173)](https://user-images.githubusercontent.com/20434963/54666818-d664c900-4b10-11e9-8b28-a366688b31be.png)
`g is being cut in the above image`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Navigate to login/register page
2. Enter the Input

**Comment by Kanishka5** [comment]
@kartikpandey2 I tried to reproduce this issue but I am not getting any such behavior.

![Screenshot from 2019-03-20 13-22-28](https://user-images.githubusercontent.com/10571896/54667802-4c6a2f80-4b13-11e9-9fec-9e731ad7881d.png)

**Comment by kartikpandey2** [comment]
@Kanishka5 Oh this seems interesting can you do me a favor, can you please share the dimension of the input box. If you are not able to reproduce this, then I guess the problem is due to different screen resolution.

**Comment by Kanishka5** [comment]
The dimension of the input box is 352 X 32.
We are using material UI framework here, which adds a responsive height to the input box so screen resolution should not be a problem.

**Comment by kartikpandey2** [comment]
@Kanishka5 Some styles might be conflicting. @Anmolbansal1 @Tushar19varshney Can you try to reproduce this.

**Comment by kush-daga** [comment]
I am able to see this in 1366x768 resolution, in 1080p it works fine
![image](https://user-images.githubusercontent.com/40840079/74826924-6ff4b600-5332-11ea-9845-bbc150b32cec.png)

**Comment by Anmolbansal1** [comment]
This issue had been already solved during previous year.
