### ISSUE TITLE
Improve login UI with social login

### ISSUE THREAD

**Issue by Kanishka5** [scorelab/fact-Bounty#236]
# Expected Behavior

The two social login buttons are not consistent and need to be at the bottom.

# Current Behavior

Inconsistent social login buttons and at the top.

![Screenshot from 2019-03-24 12-07-34](https://user-images.githubusercontent.com/10571896/54875951-f1e01480-4e2d-11e9-8770-fcb1d0f3cccf.png)

**Comment by Kanishka5** [comment]
I am working on it

**Comment by Tushar19varshney** [comment]
@Kanishka5 
I think social login button at top is not a bad option too as most of the websites have it at the top. You can add OR  text and horizontal line to segregate the manual login form and OAuth button 😊

**Comment by Kanishka5** [comment]
@Tushar19varshney Yes thank you!, OR will work fine, but the inconsistent FB and google button are not looking good, I am changing that.
