### ISSUE TITLE
404 page displayed below each page.

### ISSUE THREAD

**Issue by Kanishka5** [scorelab/fact-Bounty#251]
# Expected Behavior

404 page should be displayed only when the route is not found.

# Current Behavior

The 404 error page is displayed below every page.

## Steps to Reproduce

1. open homepage/ about/ signup/ login page
2. 404 error page is displayed below the current page

As the 404 component is set to route with no path it will be rendered every time.

![Screenshot from 2019-03-26 19-44-09](https://user-images.githubusercontent.com/10571896/55004120-a2e9d900-4fff-11e9-9189-1e8f9be969e9.png)

![Screenshot from 2019-03-26 19-39-02](https://user-images.githubusercontent.com/10571896/55004154-b432e580-4fff-11e9-8d4b-d945463c9d3e.png)

![Screenshot from 2019-03-26 19-39-30](https://user-images.githubusercontent.com/10571896/55004161-b7c66c80-4fff-11e9-83f9-ad104fcbe60b.png)

![Screenshot from 2019-03-26 19-39-43](https://user-images.githubusercontent.com/10571896/55004173-bbf28a00-4fff-11e9-89af-0bac8312ba97.png)

**Comment by Kanishka5** [comment]
I am working on it.

**Comment by kartikpandey2** [comment]
@Kanishka5 My bad , I fixed this shall I make PR .?

**Comment by Kanishka5** [comment]
@kartikpandey2 okay :+1:
