### ISSUE TITLE
About page is empty

### ISSUE THREAD

**Issue by thivatm** [scorelab/fact-Bounty#255]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

About page should have necessary details about the application and should have a proper design. So that users can easily understand and get an idea about the application.

# Current Behavior

About page is empty

# Failure Information (for bugs)

None

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open home page and then navigate to About page (About page will be empty)

**Comment by Tushar19varshney** [comment]
@thivatm In **Steps to Reproduce** you have to state down the steps to reproduce the issue (for future references)

**Comment by thivatm** [comment]
> @thivatm In **Steps to Reproduce** you have to state down the steps to reproduce the issue (for future references)

Edited the issue Thanks for the feedback.
