### ISSUE TITLE
News items are not responsive to different display sizes

### ISSUE THREAD

**Issue by thivatm** [scorelab/fact-Bounty#259]
# Prerequisites

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

News items should be responsive to different sizes of displays. Especially for mobile devices.

# Current Behavior

Currently the news items are non responsive and it doesn't show the details properly.

## Steps to Reproduce

1. Navigate to the home page where news items are displayed
2. Open the developer console in your browser and toggle device toolbar
3. Select a mobile device in the options at the top.

## Failure Logs
![2019-03-29 07_53_59-](https://user-images.githubusercontent.com/25591638/55205225-00e11100-51f8-11e9-8ca6-b9b00559eb50.png)
![2019-03-29 07_53_34-](https://user-images.githubusercontent.com/25591638/55205228-02aad480-51f8-11e9-9c5a-b766c8b4ccdf.png)

**Comment by Kanishka5** [comment]
I will work on the issue

**Comment by thivatm** [comment]
> I will work on the issue

@Kanishka5 I have already fixed this issue shall I make a PR if you haven't started or fixed it yet?

![2019-03-30 00_13_33-Fact-Bounty](https://user-images.githubusercontent.com/25591638/55256000-0420df00-5282-11e9-82aa-052f8a86c7e0.png)
