### ISSUE TITLE
Needs a README.md

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/fact-Bounty#3]
We need a README.md to get to know about this project more. With the following added, 

1.  About
2.  User Guide
 a.  How to setup
 b. How to use
4.  How to contribute

**Comment by aswinshenoy** [comment]
can I work on this issue?

**Comment by crownedlake** [comment]
@agentmilindu I can happily help with the readme.me 
I am already in the glitter face bounty group and would update the readme once something has been done.
Is there anything else should i do?

**Comment by shehand** [comment]
working on this

**Comment by agentmilindu** [comment]
Work on README.md structure first. Refer https://github.com/leopardslab/Dunner/blob/master/README.md

**Comment by crownedlake** [comment]
@agentmilindu On it

**Comment by crownedlake** [comment]
@agentmilindu the structure is clear to me and have cleared brushed my markdown skills in meantime

**Comment by ivantha** [comment]
Readme should contain a proper background and description about the project.

**Comment by Anmolbansal1** [comment]
@ivantha since now this repository has a well instructive readme file, should I close this issue??

**Comment by ivantha** [comment]
Okay. Lets go ahead and close this for now,
