### ISSUE TITLE
Redesign posts cards and post page and implement

### ISSUE THREAD

**Issue by wdevon99** [scorelab/fact-Bounty#357]
- **Redesign posts cards and post page** and implement
- **Currently** the posts page is not having a good design and not responsive

**Comment by wdevon99** [comment]
![Posts](https://user-images.githubusercontent.com/28486947/60232392-24306080-98ba-11e9-9cb4-f89eba0efbf6.png)

Wireframe for post page is attached above!

**Comment by root5533** [comment]
The posts page will have infinite scrolling so we dont need pagination buttons. Also how will the user see whether the news is true or fake? Will it be implemented as the same way it is currently implemented at the moment ?

**Comment by wdevon99** [comment]
> The posts page will have infinite scrolling so we dont need pagination buttons. Also how will the user see whether the news is true or fake? Will it be implemented as the same way it is currently implemented at the moment ?

Alright, will remove the pagination! And yeah, will add a bar in the side to indicate the validity of the news! Red = fake, Yellowish = Neutral, Green = true

**Comment by ivantha** [comment]
@root5533 @wdevon99 It would be better if the UI layout of the FactBounty is somewhat close to a social/news site etc. Currently it looks like a barebone site created to advertise a company using a generic template (Home, About, Contact us, Login etc)

**Comment by root5533** [comment]
Yes we do need to take a look into this. @wdevon99 and I will come up with something after some discussions

**Comment by wdevon99** [comment]
![PostsNew](https://user-images.githubusercontent.com/28486947/60251965-1ba24f00-98e7-11e9-93fa-1431e47dc3c4.png)

Redesigned the post list

**Comment by Anmolbansal1** [comment]
@wdevon99 It would be great if we can add word limit to text, like in third post we can reduce text and add ... instead
