### ISSUE TITLE
Navbar and loader style style clash

### ISSUE THREAD

**Issue by wdevon99** [scorelab/fact-Bounty#387]
# Prerequisites
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
- The styling of the Navbar and loader and loader should be consistent in the dev server and production build

# Current Behavior
- Navbar and loader style is changed when a production build is made

## Steps to Reproduce
- Create a production build of the react app

**Comment by wdevon99** [comment]
@root5533 , this issue is not only in prod build, it comes in dev server also, can you look into this, its due to the 

> external.css

file you added, i am not sure what will happen to the twitter graph if i remove it so i think you are the best person to look into this. :)

**Comment by wdevon99** [comment]
<img width="1679" alt="Screen Shot 2019-07-31 at 8 25 33 AM" src="https://user-images.githubusercontent.com/28486947/62180225-e026f480-b36c-11e9-8805-8725952e52cf.png">
<img width="292" alt="Screen Shot 2019-07-31 at 8 25 38 AM" src="https://user-images.githubusercontent.com/28486947/62180226-e0bf8b00-b36c-11e9-8bbd-08c67c7a4412.png">

**Comment by wdevon99** [comment]
@root5533 this issue can be closed yeah?

**Comment by root5533** [comment]
Yes this is resolved.
