### ISSUE TITLE
Issue with running Frontend

### ISSUE THREAD

**Issue by Danushka96** [scorelab/fact-Bounty#39]
Just pulled the latest patch displays this error: 

![screenshot at 2019-02-21 13-46-27](https://user-images.githubusercontent.com/12469768/53153968-9842bb00-35df-11e9-8c37-887110915779.png)

**Comment by Anmolbansal1** [comment]
Can you elaborate more, it is working correctly on my desktop

**Comment by Danushka96** [comment]
My Bad! Issue is with Firefox, Working on chrome! Thanks!! :+1:
