### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by Danushka96** [scorelab/fact-Bounty#4]
Installation of both Server and Client was successful. But when I run the client and load in browser It shows this error. 

![image](https://user-images.githubusercontent.com/12469768/52519682-3d2ad300-2c85-11e9-9e2f-677b2cdbc26e.png)

**Comment by shalithasuranga** [comment]
Hi.. @Danushka96  Please install https://github.com/zalmoxisus/redux-devtools-extension and try

**Comment by Danushka96** [comment]
@shalithasuranga It worked. Thanks..

**Comment by ankitjena** [comment]
@shalithasuranga  Thanks
