### ISSUE TITLE
When try to login from react, backend not responding!

### ISSUE THREAD

**Issue by Danushka96** [scorelab/fact-Bounty#41]
When login button pressed console shows that 404 not found for the URL and backend console show this error, Any fix? 
![screenshot at 2019-02-21 16-56-13](https://user-images.githubusercontent.com/12469768/53165928-f4b2d400-35f9-11e9-90a7-5eb7889e59e6.png)

**Comment by Pradip-001** [comment]
is it sending Email not found response?, if so then there is email mismatch

**Comment by Danushka96** [comment]
Something like this in both login and register? 

![screenshot at 2019-02-21 18-32-31](https://user-images.githubusercontent.com/12469768/53170821-14042e00-3607-11e9-962b-a9fd3d696754.png)
![screenshot at 2019-02-21 18-31-50](https://user-images.githubusercontent.com/12469768/53170823-149cc480-3607-11e9-8fac-1fb4a0fc3af1.png)

**Comment by shehand** [comment]
The problem is in the UI. The name field is requires (there is a name field also) but it is not shown due to bad UI design. When the name field is not empty the registrations will be successful.

**Comment by Danushka96** [comment]
Fixed with #46 this PR!
