### ISSUE TITLE
Add new crawlers files

### ISSUE THREAD

**Issue by JanukaD** [scorelab/fact-Bounty#416]
- [✓] I am running the latest version
- [✓ ] I checked to make sure that this issue has not already been filed

# Expected Behavior

To add, the more web crawlers files for different news sites.

# Current Behavior

Currently, web crawlers files are created only for the limited number of news sites.

**Comment by ivantha** [comment]
@JanukaD This is not a proper issues. You have to specify the sites that the crawlers should be added. 
Therefore I am closing this.
