### ISSUE TITLE
Add new crawlers files

### ISSUE THREAD

**Issue by JanukaD** [scorelab/fact-Bounty#417]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✓] I am running the latest version
- [✓] I checked to make sure that this issue has not already been filed

# Expected Behavior

To add, the more web crawlers files for following news sites;

- http://sinhala.adaderana.lk/morehotnews.php
- https://www.newsfirst.lk/sinhala/category/local/
- http://www.hirunews.lk/sinhala/local-news.php
- http://gossip.hirufm.lk/gossipnews/
- https://www.lankahotnews.net
- http://gossip.shaafm.lk/gossipnews/
-  http://sinhala.lankahitgossip.com/category/hit-gossip-news/
- http://www.rategossip.com/all-page.html
- http://nethgossip.lk/category/9

# Current Behavior

Currently, web crawlers files are created only for the limited number of news sites.

**Comment by Anmolbansal1** [comment]
@ivantha Can you tell whether we need more crawlers, if yes then we can look at the pull request.
