### ISSUE TITLE
in fact-bounty-client  TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by Pradip-001** [scorelab/fact-Bounty#42]
after running npm install and npm start , i get this error in the browser,
is there any step i'm missing? is there any environment variable need to be set in .env?

![screen shot 2019-02-21 at 5 12 24 pm](https://user-images.githubusercontent.com/26284401/53166696-0dbc8480-35fc-11e9-8235-8e9f4eeca032.png)

**Comment by Pradip-001** [comment]
@Anmolbansal1 , @ivantha , @root5533  can you help me with this?

**Comment by Tushar19varshney** [comment]
@Pradip-001 Take a look at closed issue [#4](https://github.com/scorelab/fact-Bounty/issues/4)

**Comment by Pradip-001** [comment]
@Tushar19varshney , thanks it worked
