### ISSUE TITLE
Navbar hover style is overflowing 

### ISSUE THREAD

**Issue by aloksingh3112** [scorelab/fact-Bounty#445]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?
![image](https://user-images.githubusercontent.com/27079355/65869113-58bf2700-e397-11e9-9a00-507849a5c6f9.png)
![image](https://user-images.githubusercontent.com/27079355/65869187-9328c400-e397-11e9-93cb-97de376e671e.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by wdevon99** [comment]
@aloksingh3112 Please run the client locally! The hosted on is not updated

**Comment by wdevon99** [comment]
Invalid Issue
