### ISSUE TITLE
Intro Section link opens in same tab

### ISSUE THREAD

**Issue by snitin315** [scorelab/fact-Bounty#450]
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

The link in intro section on landing page must open in a new tab 

# Current Behavior
The link opens in the same tab.

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. go to [http://www.fact-bounty.org/](http://www.fact-bounty.org/)
2. click on `INTRO`
3. you get it...

**Comment by Anmolbansal1** [comment]
@snitin315 The current website deployed on http://www.fact-bounty.org/ is just a placeholder website, the real project website is yet to be deployed. You can check the frontend by running react server.
