### ISSUE TITLE
Docker compose build error

### ISSUE THREAD

**Issue by codermanu** [scorelab/fact-Bounty#451]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Docker images should be built

# Current Behavior

Docker image building stops with an error in environment variable

# Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/30180162/69787723-11141a80-11e3-11ea-8e89-252922d4dfc4.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run `docker-compose up` in the root directory
2. you get it...

## Failure Logs

![image](https://user-images.githubusercontent.com/30180162/69787723-11141a80-11e3-11ea-8e89-252922d4dfc4.png)

**Comment by codermanu** [comment]
### Solution
Update Read me to use `EXPORT` only with `docker build` and remove `EXPORT` in `docker compose`

**Comment by root5533** [comment]
@codermanu yes go ahead.
