### ISSUE TITLE
Error when run the project

### ISSUE THREAD

**Issue by Binurim** [scorelab/fact-Bounty#453]
# Prerequisites

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

When start the server (localhost:3000) it should land the home page.

# Current Behavior

It gives an error

# Failure Information (for bugs)

![fact1](https://user-images.githubusercontent.com/25398856/70296482-d4fb3e00-1810-11ea-9148-948237b6038a.png)

## Steps to Reproduce

1. Following steps in README file
2. Start the server by  npm start
3. you get it...

## Failure Logs
![f2](https://user-images.githubusercontent.com/25398856/70297523-7b950e00-1814-11ea-872d-2a11aeba5f1f.png)

**Comment by wdevon99** [comment]
Did you include .env in the react app?

REACT_APP_GOOGLE_CLIENT_ID=""
REACT_APP_FACEBOOK_CLIENT_ID=""
REACT_APP_OAUTHD_KEY=""
REACT_APP_OAUTHD_URL=""

It can be found as the env example file inside the react project! @Binurim

**Comment by Binurim** [comment]
It works. Thank You

**Comment by root5533** [comment]
@Binurim if there were any steps missing in the README file in order to run the app, please create an issue and if possible create a PR adding those steps. Thanks. Ill close this issue.
