### ISSUE TITLE
Login glitch 

### ISSUE THREAD

**Issue by kunalbhatia18** [scorelab/fact-Bounty#454]
# Prerequisites
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
# Expected Behavior

We are supposed to be logged in or signed up when we click the button of signing/log up with facebook/google.

# Current Behavior
Currently, it does nothing and the button turns white like this 
![Screenshot 2019-12-10 at 1 39 15 PM](https://user-images.githubusercontent.com/39365087/70507510-81f7f280-1b52-11ea-8591-fa19c948da44.png)

# Failure Information (for bugs)

This is a bug as it fails to connect us to facebook or google but it enables to connect to twitter when logged in and when we click the about button. So this is a resolvable issue

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Running the project fact-bounty on localhost your system
2. Try to login via Facebook/google
3. It doesn't get us signed up or logged in if not done manually by adding name and email and password

## Failure Logs

![Screenshot 2019-12-10 at 1 46 39 PM](https://user-images.githubusercontent.com/39365087/70507988-84a71780-1b53-11ea-817e-32adfac60b5e.png)

**Comment by carpecodeum** [comment]
is this open?

**Comment by wdevon99** [comment]
do you add the relevant keys in the .env file? @kunalbhatia18

**Comment by kunalbhatia18** [comment]
@wdevon99 I added REACT_APP_OAUTHD_KEY and REACT_APP_OAUTHD_URL to set up the project.

**Comment by mgautam98** [comment]
@kunalbhatia18 is this issue resolved?
