### ISSUE TITLE
Complete documentation of stories route

### ISSUE THREAD

**Issue by Anmolbansal1** [scorelab/fact-Bounty#468]
# Context

The documentation of flask app is hosted with `flagger` library and it can be viewed on local instance of app at url `https://localhost:5000/apidocs`. It serves documentation from files in fact-bounty-flask/docs/*.yml

# Requirement

Complete the documentation of below listed routes based on corresponding functions
- /api/stories/all   
- /api/stories/change-vote-count
- /api/stories/get-range/<int:page>      
- /api/stories/get/<string:id>      
- /api/stories/load-user-votes

# Current Behaviour

Currently it displays limited documentation of stories route

**Comment by hv7214** [comment]
@Anmolbansal1 please close this issue. It's already complete in #508.
