### ISSUE TITLE
Add documentation of users route

### ISSUE THREAD

**Issue by Anmolbansal1** [scorelab/fact-Bounty#469]
# Context

The documentation of flask app is hosted with `flagger` library and it can be viewed on local instance of app at url `https://localhost:5000/apidocs`. It serves documentation from files in fact-bounty-flask/docs/*.yml

# Requirement

Complete the documentation of below listed routes based on corresponding functions
- /api/users/login             
- /api/users/logout_access     
- /api/users/logout_refresh    
- /api/users/oauth              
- /api/users/register          
- /api/users/token_refresh

# Current Behaviour

Currently it displays limited documentation of stories route

**Comment by 2knal** [comment]
@Anmolbansal1, can I please work on this issue?

**Comment by Anmolbansal1** [comment]
@2knal Yes sure :smile:

**Comment by hv7214** [comment]
@2knal i guess you are not working on this, so i am picking this issue.

**Comment by 2knal** [comment]
@hv7214, sorry for holding onto it. You can work on it :)

**Comment by hv7214** [comment]
Thanks @2knal
