### ISSUE TITLE
No such file or directory: 'requirement.txt'

### ISSUE THREAD

**Issue by Raj2367** [scorelab/fact-Bounty#484]
# Expected Behavior

In Readme in the 'setup flask server', there is a sub-part 'install your requirements'.

# Current Behavior

There is no requirement.txt present in that directory

**Comment by Raj2367** [comment]
During setup for this project I am getting this error. Please guide me how should I approach to the error.

**Comment by hv7214** [comment]
You can find `requirement.txt` in **fact-bounty-flask** folder. Make sure you are running `pip install -r requirements.txt` command in above mentioned folder.

**Comment by Raj2367** [comment]
Thank you. It worked.
