### ISSUE TITLE
jinja2.exceptions:Template not found

### ISSUE THREAD

**Issue by rajprakash00** [scorelab/fact-Bounty#519]
# Prerequisites

-  [x] I am running the latest version

-  [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Server should respond and `index.html` file should be present beforehand in templates folder

# Current Behavior

Except `localhost:5000/apidocs` all endpoints are non-functional.
`jinja2.exceptions.TemplateNotFound: index.html`

# Failure Information (for bugs)

## Steps to Reproduce

1. Start the server 
2. Make any request  like `localhost:5000` except `localhost:5000/apidocs`

## Context
<b>Setup</b>:Elementary OS. Firefox. python3

## Failure Logs

![Screenshot_2020-02-09 jinja2 exceptions TemplateNotFound index html Werkzeug Debugger](https://user-images.githubusercontent.com/42652941/74098529-491ece80-4b3f-11ea-8d4a-e129cbfa4787.png)

**Comment by Anmolbansal1** [comment]
@rajprakash00 The default route serves the react build which can be generated by production build in react, so in development this route serves nothing.

**Comment by rajprakash00** [comment]
Thanks @Anmolbansal1 !I just figured out it and  I kept index.html in build folder under api  and made changes in app.py of api and it's now working.
