### ISSUE TITLE
A different version of eslint was detected higher up in the tree in the react-scripts package.

### ISSUE THREAD

**Issue by Saad2714** [scorelab/fact-Bounty#52]
Failure Information (for bugs)
Different version of eslint was installed by npm package manager(package.json)

Steps to Reproduce
Changing the eslint version helps solve this issue.

![screenshot from 2019-02-24 23-02-50](https://user-images.githubusercontent.com/44060028/53302895-ae73a400-3889-11e9-90a9-ac3260d58bdb.png)

![screenshot from 2019-02-24 23-03-00](https://user-images.githubusercontent.com/44060028/53302889-a1ef4b80-3889-11e9-997a-39e7c75cc55e.png)

**Comment by Saad2714** [comment]
I am currently working on this issue

**Comment by Saad2714** [comment]
I have created a PR #53 solving this issue, please review @ivantha @root5533

**Comment by Anmolbansal1** [comment]
I think you have installed eslint manually, you can try running `npm install` in project

**Comment by Saad2714** [comment]
I followed the instructions provided in the README and I am facing this problem even on another system, can you please try it once?

**Comment by ganeshpatro321** [comment]
@Anmolbansal1 @Saad2714 I think this issue should be resolved ASAP.

**Comment by Saad2714** [comment]
I have tried to solve this issue in PR #53. Please review this ASAP or fix this bug as it is a hurdle when trying to solve other issues. @ivantha @root5533
