### ISSUE TITLE
Project web site redirects to malware domain

### ISSUE THREAD

**Issue by spdustin** [scorelab/fact-Bounty#551]
The project web site `http://www.fact-bounty.org/` (not linked) currently redirects to `http://survey-smiles.com`, which hosts [malware](https://otx.alienvault.com/indicator/domain/survey-smiles.com) (link goes to AlienVault IOC report for that malware domain).

```
> curl -I http://www.fact-bounty.org/

HTTP/1.1 302 Found
cache-control: max-age=0, private, must-revalidate
connection: close
content-length: 11
date: Wed, 29 Apr 2020 22:28:11 GMT
location: http://survey-smiles.com
server: nginx
set-cookie: sid=b60c165c-8a68-11ea-bf68-c72cddcbf813; path=/; domain=.fact-bounty.org; expires=Tue, 18 May 2088 01:42:19 GMT; max-age=2147483647; HttpOnly
```

**Comment by Lalit14** [comment]
i am looking for to contribute to this issue , waiting for your reply
