### ISSUE TITLE
login from navbar is not working

### ISSUE THREAD

**Issue by kartikpandey2** [scorelab/fact-Bounty#62]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
Click on the login menu item in navbar should redirect me to the login page

# Current Behavior
The login menu item is not redirecting 

## Steps to Reproduce
1. Navigate to route '/'
2. Click dropdown in the navbar and click login

**Comment by DeViL3998** [comment]
Is this issue open?If yes I would like to work on it.
