### ISSUE TITLE
Adding flow types to react components

### ISSUE THREAD

**Issue by akata01** [scorelab/fact-Bounty#65]
# Expected Behavior

Adding flow types to react components will help us make sure our react components are passed with correct props and helps validate our components.

# Current Behavior
Currently the props are not validated using flow or either by prop-types.
What is the current behavior?

**Comment by akata01** [comment]
I am working on it.

**Comment by ivantha** [comment]
@Tushar19varshney Is this issue resolved?

**Comment by Tushar19varshney** [comment]
@ivantha Now in every component, there is prop-type validation implemented, so the issue for prop-type validation is currently solved.
