### ISSUE TITLE
Improve UI of login page

### ISSUE THREAD

**Issue by kartikpandey2** [scorelab/fact-Bounty#68]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Login route UI can be improved
Presently It is untidy, 
- Labels are after input fields
- Login div is touching left margin of the body

**Comment by Pradip-001** [comment]
Someone is already working on this
