### ISSUE TITLE
Adding docker support for the application

### ISSUE THREAD

**Issue by YashMeh** [scorelab/fact-Bounty#71]
## Description
***
Adding docker support for the project .

## Mocks
***
starting the application on executing
```bash
docker-compose up
```
## Acceptance Criteria
***
## Update[Required]
- [ ]  Adding a Dockerfile to the client and server separately.
- [ ] Adding a docker-compose.yml to the root.
- [ ] Updating the README file.
## Definition of Done
- [ ] Successfully building the app.
- [ ] Completion of above acceptance criteria.
- [ ] Approval by mentor.
## Estimation
***
3 hours.

**Comment by Anmolbansal1** [comment]
I am working on this already

**Comment by YashMeh** [comment]
@Anmolbansal1 fine I'll close it .. :)
