### ISSUE TITLE
Requires changes in readme for cloning repo

### ISSUE THREAD

**Issue by prijeshb** [scorelab/fact-Bounty#78]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

1. Fork repo 
2. Once you've forked this repo, clone the repository to your local machine using following command

git clone https://github.com/<YOUR_USERNAME>/fact-Bounty.git

# Current Behavior

It states as  https://github.com/scorelab/fact-Bounty.git

## Context

It is always good to fork and follow pull request from local repo

**Comment by ivantha** [comment]
This is not necessary.
