### ISSUE TITLE
Add Forgot password feature

### ISSUE THREAD

**Issue by ganeshpatro321** [scorelab/fact-Bounty#79]
# Expected Behavior

There should be a button in the login page which will send an email to the user to reset the password.

# Current Behavior

There is no such feature present now.

**Comment by Anmolbansal1** [comment]
I am interested in working on backend of it

**Comment by ganeshpatro321** [comment]
I am taking up this issue. @ivantha .

**Comment by Anmolbansal1** [comment]
Let's collaborate on this issue @ganeshpatro321

**Comment by ganeshpatro321** [comment]
We will majorly have backend work in this issue, we cannot proceed with things, we will have to discuss things with mentors @ivantha  regarding what service will we use for mailing purposes and all.
@Anmolbansal1

**Comment by Anmolbansal1** [comment]
Okay let's wait for some input from mentor

**Comment by ivantha** [comment]
@ganeshpatro321 @Anmolbansal1 You can go ahead and use Google SMTP server.

**Comment by ivantha** [comment]
@Anmolbansal1 What is the status on this?

**Comment by ganeshpatro321** [comment]
Me and @Anmolbansal1 are working on this issue, @ivantha 
We have started working on this issue.

**Comment by hv7214** [comment]
Anyone up on this issue? I am willing to take this.

**Comment by Anmolbansal1** [comment]
Go ahead :smile:
