### ISSUE TITLE
Change the node API to Flask

### ISSUE THREAD

**Issue by ivantha** [scorelab/fact-Bounty#80]
As per the future plans, the new requirement is to implement the backend API in Python (Flask). 

This will allow better integration between the scrappy crawlers and the machine learning models in the future. 

All the codebase written in Node should be removed after migrating to Flask.

**Comment by Saad2714** [comment]
I would like to work on this issue..

**Comment by Anmolbansal1** [comment]
I have experience with working on flask, I would like to work on it

**Comment by Tushar19varshney** [comment]
I am also comfortable in python and flask.
Let's work together on this issue.:smiley:

**Comment by rajdeepbharati** [comment]
I'm also comfortable in building APIs with Flask. I would like to work on this too 👍
