### ISSUE TITLE
Move to an elastic db

### ISSUE THREAD

**Issue by ivantha** [scorelab/fact-Bounty#82]
The database should be moved from MongoDB to an Elastic SQL Database.

**Comment by Pradip-001** [comment]
I would like to work on this, I have some very basic knowledge of elastic, but still need to learn it

**Comment by Tushar19varshney** [comment]
I would also like to work on it.

**Comment by siddhant1** [comment]
Would love to work on this as well

**Comment by akata01** [comment]
I would to work on this. I will start by writing a pipeline for scrapy to ES. @ivantha do you have any specific pointers regarding this ?
