### ISSUE TITLE
Need modification in license file

### ISSUE THREAD

**Issue by vivonk** [scorelab/fact-Bounty#9]
Some fields should be modified in the LICENSE file so please update those

**Comment by ivantha** [comment]
@vivonk Can you please elaborate?

**Comment by vivonk** [comment]
I meant please review the project licence file and check if any of the field like org name, org project name, author are filled correctly or not.

**Comment by vivonk** [comment]
Copyright [yyyy] [name of copyright owner]
This field needed to be filled correctly
